"use strict";

const assert = require("assert/strict");
const fs = require("fs");

const manifest = JSON.parse(fs.readFileSync("extension/manifest.json", "utf8"));
const app = fs.readFileSync("public/app.js", "utf8");
const html = fs.readFileSync("public/index.html", "utf8");
const worker = fs.readFileSync("extension/service-worker.js", "utf8");
const broker = fs.readFileSync("functions/index.js", "utf8");
const brokerCore = fs.readFileSync("functions/broker-core.js", "utf8");
const firebase = JSON.parse(fs.readFileSync("firebase.json", "utf8"));

assert.equal(manifest.version, "0.13.1");
assert.match(worker, /AUTH_TIMEOUT_MINUTES = 15/);
assert.match(worker, /RUN_TTL_MS = 20 \* 60 \* 1000/);
assert.match(app, /POLL_TIMEOUT_MS = 20 \* 60 \* 1000/);
assert.match(fs.readFileSync("extension/content-script.js", "utf8"), /MAX_IDENTITY_ATTEMPTS = 900/);
assert.equal(manifest.incognito, "spanning");
assert.equal(manifest.permissions.includes("nativeMessaging"), false);
assert.equal(manifest.permissions.includes("alarms"), true);
assert.equal(manifest.permissions.includes("storage"), true);
assert.equal(manifest.host_permissions.includes("http://127.0.0.1/*"), false);
assert.equal(manifest.host_permissions.includes("https://identitytoolkit.googleapis.com/*"), true);
assert.equal(manifest.host_permissions.includes("https://us-central1-poc-after-sso-login-gemini.cloudfunctions.net/*"), true);
assert.match(app, /PROTOCOL_VERSION = 10/);
assert.match(app, /type: "AUTHENTICATE_POC"/);
assert.match(app, /type: "START_AGENT"/);
assert.doesNotMatch(app, /type: "POST_PROMPT"/);
assert.doesNotMatch(app, /accounts:signInWithPassword|input.*password/i);
assert.match(app, /pocIdToken/);
assert.doesNotMatch(app, /LOGIN_DIGEST|crypto\.subtle/);
assert.match(html, /POC login/);
assert.match(html, /isolated session/);
assert.match(html, /value="O1234567"[^>]*readonly/);
assert.doesNotMatch(html, /prompt-title|prompt-button|Gemini Prompt/);
assert.match(worker, /incognito: true/);
assert.match(worker, /state: "minimized"/);
assert.match(worker, /accounts:lookup/);
assert.doesNotMatch(worker, /accounts:signInWithPassword/);
assert.match(worker, /authenticatePoc/);
assert.match(worker, /getGoogleCredential/);
assert.match(worker, /CREDENTIAL_BROKER_URL/);
assert.match(worker, /fetch\(CREDENTIAL_BROKER_URL/);
assert.doesNotMatch(worker, /sendNativeMessage|NATIVE_HOST/);
assert.match(worker, /POC_AUTH_REQUIRED/);
assert.match(worker, /isAllowedIncognitoAccess/);
assert.match(worker, /chrome\.storage\.session/);
assert.match(worker, /AUTH_TIMEOUT/);
assert.doesNotMatch(worker, /chrome\.storage\.(local|sync)/);
assert.match(broker, /defineSecret\("GEMINI_TARGET_PASSWORD"\)/);
assert.match(broker, /defineSecret\("POC_FIREBASE_PASSWORD"\)/);
assert.match(broker, /verifyIdToken/);
assert.match(broker, /accounts:signInWithPassword/);
assert.match(broker, /minInstances: 0/);
assert.match(brokerCore, /chrome-extension:\/\/jeenmgigpkffleijbmfciffiodlcdafh/);
assert.match(brokerCore, /PROTOCOL_VERSION = 10/);
assert.match(worker, /documentIds/);
assert.match(worker, /webNavigation\.getFrame/);
assert.match(worker, /windows\.getAll/);
assert.match(worker, /credentialState/);
assert.match(worker, /credentialSubmitted/);
assert.match(worker, /INJECTING_PASSWORD/);
assert.match(worker, /OPENING_ISOLATED_GEMINI_TAB/);
assert.match(worker, /chrome\.tabs\.create/);
assert.match(worker, /chrome\.tabs\.reload/);
assert.match(worker, /chrome\.tabs\.remove/);
assert.match(worker, /geminiReloaded/);
assert.doesNotMatch(html, /type=["']password["']/i);
assert.equal(firebase.auth.providers.emailPassword, true);
assert.equal(firebase.functions.source, "functions");
assert.equal(firebase.functions.runtime, "nodejs22");
assert.doesNotMatch(firebase.hosting.headers[0].headers[0].value, /identitytoolkit\.googleapis\.com/);
assert.doesNotMatch(`${app}\n${html}\n${worker}\n${broker}\n${brokerCore}`, /@[s]{2}w0rd/i);
assert.doesNotMatch(worker, /chrome\.cookies|chrome\.debugger/);

console.log("PASS manifest-v3-https-broker");
console.log("PASS no-secret-in-source");
console.log("PASS static-hosted-agent-launcher");
console.log("PASS isolated-login-contract");
console.log("PASS firebase-auth-is-real-and-extension-gated");
console.log("PASS no-password-field-on-hosted-page");
console.log("PASS backend-secret-firebase-and-extension-origin-gate");
console.log("PASS exact-document-and-fresh-incognito-gates");
console.log("PASS isolated-new-gemini-tab-reload-and-single-tab-contract");
